#!/usr/bin/env bash
set -euo pipefail

VERSION="${DUCKDB_VERSION:-1.4.1}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE_DIR="${ROOT_DIR}/.duckdb"
INSTALL_DIR="${CACHE_DIR}/${VERSION}"
ENV_FILE="${CACHE_DIR}/env.sh"

detect_dist() {
  local os arch
  os="$(uname -s)"
  arch="$(uname -m)"

  case "${os}" in
    Darwin)
      case "${arch}" in
        arm64) echo "osx-universal" ;;
        x86_64) echo "osx-universal" ;;
        *)
          echo "Unsupported macOS architecture: ${arch}" >&2
          return 1
          ;;
      esac
      ;;
    Linux)
      case "${arch}" in
        x86_64|amd64) echo "linux-amd64" ;;
        aarch64|arm64) echo "linux-arm64" ;;
        *)
          echo "Unsupported Linux architecture: ${arch}" >&2
          return 1
          ;;
      esac
      ;;
    *)
      echo "Unsupported operating system: ${os}" >&2
      return 1
      ;;
  esac
}

DIST="$(detect_dist)"
ZIP_NAME="libduckdb-${DIST}.zip"
DOWNLOAD_URL="https://github.com/duckdb/duckdb/releases/download/v${VERSION}/${ZIP_NAME}"

mkdir -p "${INSTALL_DIR}"
pushd "${INSTALL_DIR}" >/dev/null

if [[ ! -f "${ZIP_NAME}" ]]; then
  echo "Downloading DuckDB ${VERSION} (${DIST})..."
  curl -L --fail --progress-bar "${DOWNLOAD_URL}" -o "${ZIP_NAME}"
else
  echo "Using cached archive ${ZIP_NAME}"
fi

if [[ ! -f "libduckdb.dylib" && ! -f "libduckdb.so" ]]; then
  echo "Extracting ${ZIP_NAME}..."
  unzip -oq "${ZIP_NAME}"
fi

if [[ ! -f "duckdb.h" ]]; then
  echo "duckdb.h missing from archive; attempting to download..."
  curl -L --fail --progress-bar "https://github.com/duckdb/duckdb/releases/download/v${VERSION}/duckdb-${DIST}.zip" -o "duckdb-headers.zip"
  unzip -oq "duckdb-headers.zip" duckdb.h duckdb.hpp || {
    echo "Failed to retrieve DuckDB headers" >&2
    exit 1
  }
fi

popd >/dev/null

{
  echo "# Generated by scripts/setup_duckdb.sh"
  echo "export DUCKDB_LIB_DIR='${INSTALL_DIR}'"
  echo "export DUCKDB_INCLUDE_DIR='${INSTALL_DIR}'"
  case "${DIST}" in
    osx-*) echo "export DYLD_FALLBACK_LIBRARY_PATH='${INSTALL_DIR}:\${DYLD_FALLBACK_LIBRARY_PATH:-}'" ;;
    linux-*) echo "export LD_LIBRARY_PATH='${INSTALL_DIR}:\${LD_LIBRARY_PATH:-}'" ;;
  esac
} > "${ENV_FILE}"

echo
echo "DuckDB ${VERSION} ready at ${INSTALL_DIR}"
echo "To activate for the current shell, run:"
echo "  source ${ENV_FILE}"
